# Generated by Django 5.0.6 on 2024-06-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_short_descriptioin_alias_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='short_description',
            new_name='shortDescription',
        ),
    ]
